version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: TalkFlowUser
      POSTGRES_PASSWORD: Motherboard2005
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      TYPEORM_CONNECTION: postgres
      TYPEORM_HOST: db
      TYPEORM_PORT: 5432
      TYPEORM_USERNAME: TalkFlowUser
      TYPEORM_PASSWORD: Motherboard2005
      TYPEORM_DATABASE: mydb
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "false"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  db-data:
